### ISSUE TITLE
thank you for your excellent job,could you please provide the train.py

### ISSUE THREAD

**Issue by zhiwenliao** [Inha-CVAI/MADGNet#2]

**Comment by zhiwenliao** [comment]
Your work is very well done. In your code, I didn't see the code for training the model; I only saw the testing code. Could you provide the code for training the model? Thank you very much.

**Comment by skawngus1111** [comment]
Thank you for the question! Our training code (train.py) is based on pranet.

https://github.com/DengPingFan/PraNet
