### ISSUE TITLE
 get_freq_indices method

### ISSUE THREAD

**Issue by Hu-Tu-Tu** [Inha-CVAI/MADGNet#5]
Thank you very much for your work. I have a question. There is a get_freq_indices method in mfmsnet.py that returns a specific frequency component. Is this frequency component fixed? Shouldn't different frequency components be determined based on different data?

**Comment by skawngus1111** [comment]
@Hu-Tu-Tu 
Thank you for your question. We selected the DCT basis following the frequency selection strategy of FCANet. Among the three available strategies—top, low, and bottom—we adopted the top strategy for our main experiments. To provide a comprehensive analysis, we also conducted experiments using the low and bottom strategies. The results of these additional experiments are included in the supplementary material.
