### ISSUE TITLE
Request for Training Code

### ISSUE THREAD

**Issue by fruit2rbj** [Inha-CVAI/MADGNet#6]
Thank you for sharing the code, but could you please provide the train.py

**Comment by skawngus1111** [comment]
Thank you for the question! Our training code (train.py) is based on pranet.

https://github.com/DengPingFan/PraNet

**Comment by waner1998** [comment]
> Thank you for the question! Our training code (train.py) is based on pranet.
> 
> https://github.com/DengPingFan/PraNet

Thank you for your wonderful work. I saw the following code in the PraNet code:
>>size_rates = [0.75, 1, 1.25]
>>  for rate in size_rates:
>>    trainsize = int(round(opt.trainsize*rate/32)*32)
>>    if rate != 1:
>>    images = F.upsample(images, size=(trainsize, trainsize), mode='bilinear', align_corners=True)
>>    gts = F.upsample(gts, size=(trainsize, trainsize), mode='bilinear', align_corners=True)

May I ask if you also used the training strategy of scaling down or scaling up the training images in this work?
Looking forward to your reply.
Sincerely,
Liu.

**Comment by skawngus1111** [comment]
@waner1998 Thank you for reply. Yes! We used same multi-scale training strategy with PraNet.
