### ISSUE TITLE
Errors raised by batchsize

### ISSUE THREAD

**Issue by waner1998** [Inha-CVAI/MADGNet#7]
Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful.
Sincerely，
https://github.com/waner1998/Replication-of-MADGNet

**Comment by skawngus1111** [comment]
@waner1998 Thank you for your attention! I saw your train.py code. However, it looks that you did not use multi-scale training strategy.

**Comment by waner1998** [comment]
> @waner1998 Thank you for your attention! I saw your train.py code. However, it looks that you did not use multi-scale training strategy.

Thank you for your reply! it did almost solve the problem after doing so. But doing so multiplies the computation by three times, which is indeed a solution.

**Comment by Szh2620** [comment]
> Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet

Hello,

May I ask if you successfully trained and tested your own dataset using this code?

**Comment by waner1998** [comment]
> > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> 
> Hello,
> 
> May I ask if you successfully trained and tested your own dataset using this code?

Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.

**Comment by Szh2620** [comment]
> > > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> > 
> > 
> > Hello,
> > May I ask if you successfully trained and tested your own dataset using this code?
> 
> Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.


Do you mean that the batch size setting affects the model's performance, and that this issue no longer exists after adding multi-scale support?

**Comment by waner1998** [comment]
> > > > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> > > 
> > > 
> > > Hello,
> > > May I ask if you successfully trained and tested your own dataset using this code?
> > 
> > 
> > Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.
> 
> Do you mean that the batch size setting affects the model's performance, and that this issue no longer exists after adding multi-scale support?

yes

**Comment by Szh2620** [comment]
> > > > > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> > > > 
> > > > 
> > > > Hello,
> > > > May I ask if you successfully trained and tested your own dataset using this code?
> > > 
> > > 
> > > Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.
> > 
> > 
> > Do you mean that the batch size setting affects the model's performance, and that this issue no longer exists after adding multi-scale support?
> 
> yes


Thank you, sir. Could you kindly provide the code? I would like to test the generalization performance on my two datasets, and I would be deeply grateful.

**Comment by waner1998** [comment]
> https://github.com/waner1998/Replication-of-MADGNet



> > > > > > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> > > > > 
> > > > > 
> > > > > Hello,
> > > > > May I ask if you successfully trained and tested your own dataset using this code?
> > > > 
> > > > 
> > > > Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.
> > > 
> > > 
> > > Do you mean that the batch size setting affects the model's performance, and that this issue no longer exists after adding multi-scale support?
> > 
> > 
> > yes
> 
> Thank you, sir. Could you kindly provide the code? I would like to test the generalization performance on my two datasets, and I would be deeply grateful.

 https://github.com/waner1998/Replication-of-MADGNet All you need to do is add multi-scale to this code, it's pretty simple.

**Comment by Szh2620** [comment]
> > https://github.com/waner1998/Replication-of-MADGNet
> 
> > > > > > > Thank you for your wonderful work! However, I reproduced the train code, the batchsize setting can greatly affect the experimental results, could you please help me to look at it? Or can you provide me with the official training code? I would be very grateful. Sincerely， https://github.com/waner1998/Replication-of-MADGNet
> > > > > > 
> > > > > > 
> > > > > > Hello,
> > > > > > May I ask if you successfully trained and tested your own dataset using this code?
> > > > > 
> > > > > 
> > > > > Yes, I trained successfully. But multi-scaling slows down the overall training dramatically, however not using this technique can be problematic. This phenomenon is rare.
> > > > 
> > > > 
> > > > Do you mean that the batch size setting affects the model's performance, and that this issue no longer exists after adding multi-scale support?
> > > 
> > > 
> > > yes
> > 
> > 
> > Thank you, sir. Could you kindly provide the code? I would like to test the generalization performance on my two datasets, and I would be deeply grateful.
> 
> https://github.com/waner1998/Replication-of-MADGNet All you need to do is add multi-scale to this code, it's pretty simple.

I will try.Wishing you good health and all the best!
